apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkIn
  labels:
    app: checkIn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkIn
  template:
    metadata:
      labels:
        app: checkIn
    spec:
      containers:
        - name: checkIn
          image: username/checkIn:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5